name: Deploy Dev (Demo)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'backend' # for submodule
      - 'frontend/**'
      - 'frontend' # for submodule

jobs:
  trigger-dev-deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: dev
      aws_region: us-east-1
    secrets: inherit
