name: Deploy Dev (Demo)

on:
  push:
    branches:
      - main

jobs:
  trigger-dev-deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: dev
      aws_region: us-east-1
      terraform_dir: terraform/environments/dev
    secrets: inherit
