name: Deploy Prod

on:
  push:
    tags:
      - 'v*' # Triggers on tagged version pushes (e.g. v*), facilitating audited deployment to the Prod environment.

jobs:
  trigger-prod-deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: prod
      aws_region: us-east-1
    secrets: inherit
