name: Reusable Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      terraform_dir:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install Python Dependencies
        run: |
          cd backend
          poetry install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false # Disable wrapper to ensure raw output in local-exec calls

      - name: Terraform Init and Apply
        run: |
          cd ${{ inputs.terraform_dir }}
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_database_password: ${{ secrets.DATABASE_PASSWORD }}
          TF_VAR_neon_api_key: ${{ secrets.NEON_API_KEY }}
          TF_VAR_backend_secret_key: ${{ secrets.BACKEND_SECRET_KEY }}
          TF_VAR_environment: ${{ inputs.environment }}
          TF_VAR_aws_region: ${{ inputs.aws_region }}
